import { spawn } from 'child_process';
import fs from 'fs/promises';
import path from 'path';
import messageBus, { EVENTS } from '../core/MessageBus.js';

class IssueAgent {
  constructor() {
    this.initialized = false;
    this.writePromise = Promise.resolve();
  }

  async init() {
    if (this.initialized) return;

    await messageBus.subscribe(EVENTS.ISSUE_REQUESTED, async (payload) => {
      console.log(`[IssueAgent] Issue creation requested for domain: ${payload.domain}`);
      try {
        await this.createIssue(payload);
      } catch (err) {
        console.error('[IssueAgent Error] Failed to create issue:', err);
      }
    });

    this.initialized = true;
    console.log('[IssueAgent] Subscribed to issue.create.requested.');
  }

  async createIssue(payload) {
    const { runId, domain, title, body, labels } = payload;
    
    const issueTitle = `[Cold Start] Test Failure on ${domain} - Run ${runId}`;
    const issueBody = `### Error Details
**Domain:** ${domain}
**Run ID:** ${runId}

**Message:**
\`\`\`text
${body || 'No error logs provided.'}
\`\`\`

---
*Auto-generated by AI Multi-Agent Test System (v2.0)*`;

    console.log(`[IssueAgent] Attempting to create GitHub issue: "${issueTitle}"...`);

    // 1. Try to create a real GitHub issue using local GitHub CLI
    try {
      const args = ['issue', 'create', '--title', issueTitle, '--body', issueBody];
      if (labels && labels.length > 0) {
        for (const label of labels) {
          args.push('--label', label);
        }
      }
      
      const res = await this.runGhCommand(args);
      console.log(`[IssueAgent] GitHub Issue created successfully: ${res}`);
      return;
    } catch (err) {
      console.warn(`[IssueAgent] GitHub CLI issue creation failed (${err.message}). Falling back to local logging.`);
    }

    // 2. Fallback: Write issue to logs/issues.json
    // Chain writes onto writePromise to serialize local file logging and prevent overwrite race conditions
    this.writePromise = this.writePromise.then(async () => {
      const logDir = path.join('logs');
      await fs.mkdir(logDir, { recursive: true });
      
      const logPath = path.join(logDir, 'issues.json');
      let issues = [];
      try {
        const fileData = await fs.readFile(logPath, 'utf-8');
        issues = JSON.parse(fileData);
      } catch (err) {
        // File doesn't exist yet
      }

      issues.push({
        runId,
        domain,
        title: issueTitle,
        body: issueBody,
        labels: labels || [],
        createdAt: new Date().toISOString()
      });

      await fs.writeFile(logPath, JSON.stringify(issues, null, 2), 'utf-8');
      console.log(`[IssueAgent] Local issue logged successfully to: ${logPath}`);
    }).catch(err => {
      console.error('[IssueAgent Error] Failed to write issue to logs/issues.json:', err);
    });

    await this.writePromise;
  }

  runGhCommand(args) {
    return new Promise((resolve, reject) => {
      const child = spawn('gh', args);
      
      let stdout = '';
      let stderr = '';
      
      child.stdout.on('data', (data) => {
        stdout += data.toString();
      });
      
      child.stderr.on('data', (data) => {
        stderr += data.toString();
      });
      
      child.on('close', (code) => {
        if (code === 0) {
          resolve(stdout.trim());
        } else {
          reject(new Error(`gh exit code ${code}: ${stderr}`));
        }
      });
      
      child.on('error', (err) => {
        reject(err);
      });
    });
  }
}

const issueAgent = new IssueAgent();
export default issueAgent;
